# Generated by Django 5.2.3 on 2025-06-24 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_cliente",
                    models.CharField(max_length=100, verbose_name="Nombre del Cliente"),
                ),
                (
                    "email_cliente",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email del Cliente"
                    ),
                ),
                (
                    "telefono_cliente",
                    models.CharField(
                        max_length=20, verbose_name="Teléfono del Cliente"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                ("pagado", models.BooleanField(default=False, verbose_name="Pagado")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En Proceso"),
                            ("listo_recoger", "Listo para Recoger"),
                            ("en_reparto", "En Reparto"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado del Pedido",
                    ),
                ),
                (
                    "notas_adicionales_cliente",
                    models.TextField(blank=True, verbose_name="Notas del Cliente"),
                ),
                (
                    "notas_adicionales_personal",
                    models.TextField(
                        blank=True, verbose_name="Notas Internas (Personal)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["-fecha_creacion"],
                        name="pedidos_ped_fecha_c_7791cc_idx",
                    ),
                    models.Index(
                        fields=["nombre_cliente"], name="pedidos_ped_nombre__97e7eb_idx"
                    ),
                    models.Index(
                        fields=["email_cliente"], name="pedidos_ped_email_c_7e384a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio Unitario ($) (al momento del pedido)",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items_pedido",
                        to="menu.producto",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pedidos.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Pedido",
                "verbose_name_plural": "Detalles de Pedido",
                "ordering": ["id"],
                "unique_together": {("pedido", "producto")},
            },
        ),
    ]
